### ISSUE TITLE
[Suggestion] Add blacklist config

### ISSUE THREAD

**Issue by FusionSwarly** [MaxenceDC/sparsestructures#1]
I know you intend to add configuration to the mod, but it'd be a good idea to add a blacklist to the config. You could add specific structures or perhaps even blacklist entire mods from being affected.

**Comment by MaxenceDC** [comment]
Thank you for your suggestion! This is a good idea, I'll definitely try to implement that in the future. I'm still very new to Minecraft modding, and I've never done config before, so the update won't come super quickly.
In the meantime, if you really need to blacklist a structure, you can achieve that by finding the config file for your structure and divide by two it's `separation` and `spacing`... It's kinda hacky, but it works. I hope you won't have to wait too long for this feature to come out!

**Comment by MaxenceDC** [comment]
Coming to this suggestion again, I think I found a good way to implement this, UX side: add structure-specific spread factor, if you want to blacklist a structure from this mod, simply use a a factor of 1, or if you want to make it more common, a factor of 1/2 for example (or even 3 if you want to make it even rarer). I might start working on it today or tomorrow.
What do you think @FusionSwarly?

**Comment by Ignat34** [comment]
Hello! Are you still working at your mode? Will it be ported to newer versions?

**Comment by FusionSwarly** [comment]
> Coming to this suggestion again, I think I found a good way to implement this, UX side: add structure-specific spread factor, if you want to blacklist a structure from this mod, simply use a a factor of 1, or if you want to make it more common, a factor of 1/2 for example (or even 3 if you want to make it even rarer). I might start working on it today or tomorrow. What do you think @FusionSwarly?

That's a much better idea! That'd be super useful.

**Comment by MaxenceDC** [comment]
> Hello! Are you still working at your mode? Will it be ported to newer versions?

@Ignat34 Unfortunately, I have loads of work to do for school, but I'll start working on it next week and during the vacations! I'll try to port it to 1.20.2 (it should already be compatible right now, you could try). I'll also work on adding the blacklist.

> That's a much better idea! That'd be super useful.

@FusionSwarly Thx! I'll try adding it next week / in two weeks.

**Comment by MaxenceDC** [comment]
Updated to 1.20.2 and configurable.
