### ISSUE TITLE
BetterEnd breaks with Sparse Structures

### ISSUE THREAD

**Issue by steve-the-player** [MaxenceDC/sparsestructures#14]
When using BetterEnd combined with Sparse structures, none of the BetterEnd biomes spawn in. This also means that the central end island (which is normally considered its own biome) doesn't spawn in any of the obsidian towers

**Comment by MaxenceDC** [comment]
Hmm, that's interesting, I'll try to reproduce this when I can.
Thank you for the report.

**Comment by MaxenceDC** [comment]
I can't reproduce this issue with a fresh install (only SparseStructures, BetterEnd, BCLib and Fabric API). Make sure the world type is set to BetterX.
