### ISSUE TITLE
Question: Am i doing this correctly?

### ISSUE THREAD

**Issue by vivagabe** [MaxenceDC/sparsestructures#20]
[sparsestructures.txt](https://github.com/MaxenceDC/sparsestructures/files/14048235/sparsestructures.txt)

Can you tell me if im adding these structures correctly? Thank you!

**Comment by MaxenceDC** [comment]
well the file has to be named sparsestructures.json5 and placed in the config folder, but other than that, if the namespaces are correct, then it should be fine.
