### ISSUE TITLE
Help with setting up the config

### ISSUE THREAD

**Issue by ghost** [MaxenceDC/sparsestructures#21]
I am an idiot who doesn't know how to write it properly and where

here's my custom config for my custom modpack

[sparsestructures.txt](https://github.com/MaxenceDC/sparsestructures/files/14086180/sparsestructures.txt)

please explain why it isn't working(I ran tests, it's not)

**Comment by ghost** [comment]
I changed to a txt format to send it into here since github doesn't allow me to send it as a .json5 file

**Comment by MaxenceDC** [comment]
[sparsestructures.json5.txt](https://github.com/MaxenceDC/sparsestructures/files/14088438/sparsestructures.json5.txt)
Here is the correct version, without comments

**Comment by ghost** [comment]
oh oh
[crash-2024-01-29_21.04.44-client.txt](https://github.com/MaxenceDC/sparsestructures/files/14088511/crash-2024-01-29_21.04.44-client.txt)

![image](https://github.com/MaxenceDC/sparsestructures/assets/79714522/dfb3a4fb-5d2c-439c-9cb1-a0f15a47b295)

**Comment by MaxenceDC** [comment]
Sorry, there were still some mistakes : 
[sparsestructures.json5.txt](https://github.com/MaxenceDC/sparsestructures/files/14088536/sparsestructures.json5.txt)

**Comment by ghost** [comment]
still
![image](https://github.com/MaxenceDC/sparsestructures/assets/79714522/26746e1d-2268-43ae-9008-e54c6543cb53)

[crash-2024-01-29_21.20.17-client.txt](https://github.com/MaxenceDC/sparsestructures/files/14088670/crash-2024-01-29_21.20.17-client.txt)
