### ISSUE TITLE
How do I make structures only slightly sparser than in Vanilla.

### ISSUE THREAD

**Issue by Sarsath** [MaxenceDC/sparsestructures#24]
In the configs, it says

> this is the main spread factor (default is 2) 

Is the spreadFactor of vanilla (that is, without the mod) 1? If not, what is it?

What would you say is the number that would separate the spawn altar and this spider dungeon in the image below by, say, 12 blocks.

![Screenshot 2024-02-07 193012](https://github.com/MaxenceDC/sparsestructures/assets/73806295/0c6164aa-cdac-4d28-8a54-9ff4496ace0e)

**Comment by MaxenceDC** [comment]
Structures are not spread out from others, only between two structures of the same pool. That being said, a bigger number means a rarer structure.
