### ISSUE TITLE
[Question] Are the custom spreadfactors affected by the global one?

### ISSUE THREAD

**Issue by 0nullfish** [MaxenceDC/sparsestructures#28]
For example, if I had a global spreadfactor of 2, but had all types of village at a custom spreadfactor of 4, would this result in villages being 8 times rarer?

**Comment by MaxenceDC** [comment]
> For example, if I had a global spreadfactor of 2, but had all types of village at a custom spreadfactor of 4, would this result in villages being 8 times rarer?

No it's overwritten, good question tho, I'll clarify that next update
