### ISSUE TITLE
Doesn't seem to work with Repurposed Structures?

### ISSUE THREAD

**Issue by V-lpen** [MaxenceDC/sparsestructures#3]
I did not test to confirm, but I still see the structures from Repurposed Structures very often, it doesn't seem like they're spread out like this mod is supposed to do

Specifically in the nether is where im noticing a lot of structures, however could It have to do with me using incendium? (Biomes only)

**Comment by MaxenceDC** [comment]
Have you tried loading the same seed with the same mods but without my mods and comparing the structures' placement ?

**Comment by MaxenceDC** [comment]
You were right, my mod was skipping Repurposed Structure's Structures because the mod uses its own random_spread for some reason.
It should be compatible in v2.1.
