### ISSUE TITLE
Structures removal

### ISSUE THREAD

**Issue by TLiG98** [MaxenceDC/sparsestructures#30]
Blacklist a certain, or multiple structures from being generated.

could be like this in the config file:

**Comment by TLiG98** [comment]
![IMG_7927](https://github.com/MaxenceDC/sparsestructures/assets/26041401/ca3f2b05-0954-478a-ab8c-00db85e2d534)

**Comment by MaxenceDC** [comment]
This is planned (but not as easy to implement).
Will let you know when this is available

**Comment by MaxenceDC** [comment]
Duplicate of #15 btw
