### ISSUE TITLE
1.20.1, SS 2.1.2 - /dumpstructuresets command does not exist

### ISSUE THREAD

**Issue by Roadhog360** [MaxenceDC/sparsestructures#31]
The mod page exclaims the following: "Tip: you can dump all structure sets to a file in the right format by using the custom command `/dumpstructuresets`"
However, this command simply does not exist. This makes it a little tricky to adjust the structures I want when I can't be sure I get them all and have to manually check the /locate autofill list.
![2024-07-08_03 28 12](https://github.com/MaxenceDC/sparsestructures/assets/11903511/545affb6-14f9-49ee-8b8d-64725ff4ae9f)
![2024-07-08_03 28 15](https://github.com/MaxenceDC/sparsestructures/assets/11903511/275ea297-af10-4d83-8701-47df6269779d)

**Comment by MaxenceDC** [comment]
This feature was added in v2.2
This version will soon be available for 1.20.1
Have a good day

**Comment by Roadhog360** [comment]
Oh

**Comment by MaxenceDC** [comment]
> Oh

Will let you know when it's out!

**Comment by Roadhog360** [comment]
Appreciated.

**Comment by MaxenceDC** [comment]
> Appreciated.

Available for Fabric 1.20.1 on Modrinth
