### ISSUE TITLE
Are Nether Fortresses more sparsed too?

### ISSUE THREAD

**Issue by ivanovic77** [MaxenceDC/sparsestructures#44]
If I have a global spread factor of 2, does this mean that Nether Fortresses are also twice more sparsed?

If the answer is yes and I want that Nether Fortresses have a vanilla separation, then I guess I have to add a custom spread factor for the Nether Fortress specifically, right?

Thanks in advance.

**Comment by MaxenceDC** [comment]
Yes you understood that correctly.
Have a nice day
