### ISSUE TITLE
Please add the config in the 1.19 version

### ISSUE THREAD

**Issue by tanyan-tanyan** [MaxenceDC/sparsestructures#6]
Hi, can you make the 1.19 version configurable? I just used your mod (1.1 version), and while it did make structures a lot less common, I've gone from like 30 structures to like 4 structures per region, which isn't necessarily ideal for my modpack. My modpack is stuck in 1.19 so I can't upgrade.

If it's not possible for any reason, would it be permissible within your license for users to modify the jar file themselves? If so, how can I go about it?

**Comment by MaxenceDC** [comment]
Thank's to #7 and @natpalmer-e4o4, this is planned!

**Comment by tanyan-tanyan** [comment]
Oh my god that is amazing!!!!

**Comment by MaxenceDC** [comment]
The update is now available on GitHub, Modrinth and soon on Curseforge (has to be approved first)
